# Generated by Django 5.2.17 on 2026-09-08 07:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('cote', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_PRET', 'En prêt'), ('EN_CONSULTATION', 'En consultation sur place'), ('PERDU', 'Perdu'), ('VOLE', 'Volé'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20)),
                ('date_acquisition', models.DateField(auto_now_add=True)),
                ('est_hors_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CdRom',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.document')),
                ('auteur_ou_editeur', models.CharField(max_length=255)),
                ('thematique', models.CharField(max_length=255)),
                ('caution_montant_requis', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            bases=('catalogue.document',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.document')),
                ('date_parution', models.DateField()),
            ],
            bases=('catalogue.document',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.document')),
                ('auteur', models.CharField(max_length=255)),
                ('consultable_uniquement_sur_place', models.BooleanField(default=False)),
            ],
            bases=('catalogue.document',),
        ),
        migrations.CreateModel(
            name='Microfilm',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.document')),
                ('document_associe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='microfilms', to='catalogue.document')),
            ],
            bases=('catalogue.document',),
        ),
    ]
