# Generated by Django 5.2.17 on 2026-09-08 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('COURRIER', 'Courrier postal'), ('EMAIL', 'E-mail')], default='COURRIER', max_length=20)),
                ('emetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_emises', to=settings.AUTH_USER_MODEL)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relances', to='circulation.pret')),
            ],
            options={
                'ordering': ('-date_emission',),
            },
        ),
    ]
