# Generated by Django 5.2.17 on 2026-09-08 07:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcranLecture',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('est_libre', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pret', models.CharField(choices=[('DOMICILE', 'Prêt à domicile'), ('SUR_PLACE', 'Consultation sur place')], max_length=20)),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_restitution', models.DateTimeField(blank=True, null=True)),
                ('montant_caution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('caution_restituee', models.BooleanField(default=False)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prets', to='adherents.adherent')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prets', to='catalogue.document')),
                ('poste_ecran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circulation.ecranlecture')),
            ],
        ),
    ]
